### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by mottosso**
Also made version semver compatible, and uploaded to PyPI.

### CODE REVIEW

**Comment by fredrikaverpil** [comment]
LGTM

**Comment by fredrikaverpil** [comment]
Btw, we're doing merge commits, right?

**Comment by mottosso** [comment]
> LGTM

Haha, had to google that. https://www.urbandictionary.com/define.php?term=LGTM

> Btw, we're doing merge commits, right?

Yeah, or how do you mean? As opposed to the newer "Squash" commits on GitHub?

**Comment by fredrikaverpil** [comment]
Yeah, I thought I could've just accepted that PR as I thought it looked good. But I wasn't sure on the next step where you're asked whether to "merge commit" or "squash and merge".

screen shot 2016-05-28 at 12 12 47

**Comment by mottosso** [comment]
Ah, yeah, merge commit.

**Pull request merged**
