### PR TITLE
Removed init() and restructured code

### PR DESCRIPTION
**Pull request by fredrikaverpil**
What do you think of this kind of approach?

With this, we get a function (`load_wrapper`) which could handle errors and you can re-order `QT_BINDING_LOAD_ORDER` to change the load order.

Fixes https://github.com/mottosso/Qt/issues/6 and https://github.com/mottosso/Qt/issues/9

### CODE REVIEW

**Comment by mottosso** [comment]
Looks good, but I wonder whether it really makes it easier to see what is happening.

**Comment by fredrikaverpil** [comment]
Would you rather see something like this?

```python
loaded = False
for binding in QT_BINDING_LOAD_ORDER:
    if not loaded:
        function_name = 'load_' + binding.lower() + '()'
        try:
            exec function_name
            loaded = True
        except ImportError:
            pass
if not loaded:
    sys.stderr.write("Qt: Could not find appropriate bindings for Qt\n")
```

**Comment by mottosso** [comment]
I'm not a fan of:

1. Needless state, `loaded = False`
2. Guessing function names, `function_name = 'load_' + binding.lower() + '()'`
3. `exec`

(1) makes it difficult to read; having to continue reading before understanding what `loaded` does. (2) Means that the name of a function is stored twice; both in the function, and once in the list of orders. Complicates maintenance. Finally (3) is just no.

The current approach (#9) isn't pretty, but it is easy to understand and maintain. We should hold on to those properties.

**Comment by mottosso** [comment]
Also bear in mind that every variable you declare at module-level is accessible via import.

```python
from Qt import loaded
# what is loaded?
```

**Comment by fredrikaverpil** [comment]
> every variable you declare at module-level is accessible via import.

Ah, that's very true. I didn't think about that.

**Pull request closed without merging**
